# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  # Dev Container updates
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "main"

  # Maven dependencies updates (Java)
  # Monitors the pom.xml on main branch
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      time: "03:00"
    target-branch: "main"
    open-pull-requests-limit: 10
    reviewers:
      - "0GiS0"
    labels:
      - "dependencies"
      - "java"
    commit-message:
      prefix: "deps(maven)"
      prefix-development: "deps(dev)"
      include: "scope"

  # Maven dependencies updates (Java) - Cucumber branch
  # Monitors the pom.xml on cucumber branch for BDD tests
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: weekly
      day: "tuesday"
      time: "03:00"
    target-branch: "cucumber"
    open-pull-requests-limit: 10
    reviewers:
      - "0GiS0"
    labels:
      - "dependencies"
      - "java"
      - "cucumber"
      - "bdd"
    commit-message:
      prefix: "deps(maven-cucumber)"
      prefix-development: "deps(dev-cucumber)"
      include: "scope"
